import type { ProviderProfilePreset } from "../../../shared/provider-profile-types"

export const PROVIDER_PROFILE_PRESETS: ProviderProfilePreset[] = [
  {
    id: "deepseek",
    name: "DeepSeek",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-v4-flash",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "dashscope-qwen",
    name: "Qwen / DashScope",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen-plus",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
      vision: true,
    },
  },
  {
    id: "kimi-moonshot",
    name: "Kimi / Moonshot",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://api.moonshot.ai/v1",
    defaultModel: "moonshot-v1-128k",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "zhipu-glm",
    name: "Zhipu / GLM",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-5.1",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://api.siliconflow.cn/v1",
    defaultModel: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
      vision: true,
    },
  },
  {
    id: "volcengine-ark",
    name: "Volcengine Ark",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultModel: "doubao-seed-code",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "baidu-qianfan",
    name: "Baidu Qianfan",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://qianfan.baidubce.com/v2",
    defaultModel: "ernie-4.5-turbo-128k",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
    },
  },
  {
    id: "tencent-hunyuan",
    name: "Tencent Hunyuan",
    region: "china",
    protocol: "openai-chat",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    defaultModel: "hunyuan-turbos-latest",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "generic-openai-chat",
    name: "Generic OpenAI-compatible",
    region: "generic",
    protocol: "openai-chat",
    baseUrl: "https://api.example.com/v1",
    defaultModel: "model-id",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
    },
  },
  {
    id: "generic-anthropic",
    name: "Generic Anthropic-compatible",
    region: "generic",
    protocol: "anthropic",
    baseUrl: "https://api.example.com/v1",
    defaultModel: "model-id",
    authMode: "x-api-key",
    targetRuntimes: ["claude", "helpers"],
    capabilities: { claude: true, helpers: true, streaming: true, tools: true },
  },
  {
    id: "litellm",
    name: "LiteLLM",
    region: "generic",
    protocol: "openai-responses",
    baseUrl: "http://127.0.0.1:4000/v1",
    defaultModel: "model-id",
    authMode: "bearer",
    targetRuntimes: ["claude", "codex", "helpers"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "ollama",
    name: "Ollama",
    region: "local",
    protocol: "openai-chat",
    baseUrl: "http://127.0.0.1:11434/v1",
    defaultModel: "gpt-oss:20b",
    authMode: "none",
    targetRuntimes: ["claude", "codex", "helpers", "local"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      local: true,
      streaming: true,
    },
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    region: "local",
    protocol: "openai-chat",
    baseUrl: "http://127.0.0.1:1234/v1",
    defaultModel: "local-model",
    authMode: "none",
    targetRuntimes: ["claude", "codex", "helpers", "local"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      local: true,
      streaming: true,
      tools: true,
    },
  },
  {
    id: "vllm-localai",
    name: "vLLM / LocalAI",
    region: "local",
    protocol: "openai-chat",
    baseUrl: "http://127.0.0.1:8000/v1",
    defaultModel: "local-model",
    authMode: "none",
    targetRuntimes: ["claude", "codex", "helpers", "local"],
    capabilities: {
      claude: true,
      codex: true,
      helpers: true,
      local: true,
      streaming: true,
    },
  },
]

export function getProviderProfilePreset(id: string | null | undefined) {
  if (!id) return undefined
  return PROVIDER_PROFILE_PRESETS.find((preset) => preset.id === id)
}
